# Nessa extensão, cuidado com o espaçamento e alinhamento do script
# texto xpto
  # espaçamento, adicionar ou excluir para evitar erros

# CI de nível 1 - disparo manual a partir de 1 clique
# Nome do pipeline
name: 'Execução manual'

# Configurar regras de execução
# Regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch, que irá dentro do 'on'
# e execução manual sempre terá workflow_dispatch

on:
  workflow_dispatch:

# trabalhos/tarefas que são executados dentro do pipeline = jobs
jobs:
  e2e-tests:
    # definir qual máquina o job vai executar
    runs-on: ubuntu-latest
    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do yarn
      - name: Instalando yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: yarn 
      
      # instalando playwright
      - name: Instalando playwright
        run: yarn playwright install
      
      # executando testes e2e no playwright
      - name: Executando testes e2e
        run: yarn run e2e