# CI de nível 3 - disparo após a conclusão de uma pipeline
name: 'Execução por deploy'

# gatilho de exec a partir de outro pipe = workflow_run
on:
  workflow_run:
    workflows: ['Execução manual']
    types:
      - completed

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    # condicionais - if
    # `${ expressão }`
    # == comparação
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando playwright
        run: yarn playwright install

      - name: Executando testes e2e
        run: yarn run e2e

      # geração e upload de relatório
      - uses: actions/upload-artifact@v4
        # caso a execução não seja cancelada, ele executa esse bloco
        # pode também ser usado com ${{ always() }}
        if: ${{ !cancelled() }}
        with:
          name: report
          path: ./playwright-report
