# CI de nível 4 - disparo dos testes dentro do pipe de dev

# - workflow n4
#   - jobs - inspeção
#       - steps - instalar deps
#       - steps - executar script de lint
#   - jobs - unidade
#       - steps - instalar deps
#       - steps - executar scripts de testes unitários
#   - jobs - e2e-tests
#       - steps - instalar deps
#       - steps - subir a aplicação localmente
#       - steps - instalar browsers/navegadores
#       - steps - executar scripts de testes e2e
#       - steps - publicar resultados de testes
#    - jobs - deploy
#       - steps - instalar deps
#       - steps - gerar artefatos de aplicação
#       - steps - publicar aplicação em algum ambiente
name: 'Execução integrado'

on:
  workflow_dispatch:

jobs:
  inspecao:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn
      
      - name: checando padronização do código
        run: yarn lint
  
  unidade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn
      
      - name: executando teste de unidade
        run: yarn test

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn 
      
      - name: Instalando playwright
        run: yarn playwright install
      
      - name: Executando testes e2e
        run: yarn run e2e
      
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: report
          path: ./playwright-report
  
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: simulação do deploy
        run: echo "simulando o deploy com sucesso"